######################################################################
# Automatically generated by qmake (3.0) Tue Mar 15 09:29:26 2016
######################################################################

QT += widgets

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
