# Generated by Django 2.0.3 on 2019-02-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='value',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
