######################################################################
# Automatically generated by qmake (3.0) Tue Mar 15 10:07:35 2016
######################################################################
QT += widgets

TEMPLATE = app
TARGET = layout
INCLUDEPATH += .

# Input
SOURCES += layout.cpp
