compile: 6.3.o \
	 6.4.o \
	 6.5.o \
	 6.6.o \
	 6.7.o \
	 factMain.o \
	 fact.o \
	 6.10.o \
	 6.11.o \
	 6.12.o \
	 6.17.o \
	 6.21.o \
	 6.22.o \
	 6.23.o \
	 6.25.o \
	 6.26.o \
	 6.27.o \
	 6.33.o \
	 6.51.o \
	 6.55.o \
	 6.56.o
	g++ -o 6.3 6.3.o
	g++ -o 6.4 6.4.o
	g++ -o 6.5 6.5.o
	g++ -o 6.6 6.6.o
	g++ -o 6.7 6.7.o
	g++ fact.o factMain.o -o 6.9
	g++ 6.10.o -o 6.10
	g++ 6.11.o -o 6.11
	g++ 6.12.o -o 6.12
	g++ 6.17.o -o 6.17
	g++ 6.21.o -o 6.21
	g++ 6.22.o -o 6.22
	g++ 6.23.o -o 6.23
	g++ 6.25.o -o 6.25
	g++ 6.26.o -o 6.26
	g++ 6.27.o -o 6.27
	g++ 6.33.o -o 6.33
	g++ 6.51.o -o 6.51
	g++ 6.55.o -o 6.55
	g++ 6.56.o -o 6.56

6.3.o: 6.3.cpp
	g++ -c 6.3.cpp

6.4.o: 6.4.cpp
	g++ -c 6.4.cpp

6.5.o: 6.5.cpp
	g++ -c 6.5.cpp

6.6.o: 6.6.cpp
	g++ -c 6.6.cpp

6.7.o: 6.7.cpp
	g++ -c 6.7.cpp

fact.o: fact.cc
	g++ -c fact.cc

factMain.o: factMain.cc
	g++ -c factMain.cc

6.10.o: 6.10.cpp
	g++ -c 6.10.cpp

6.11.o: 6.11.cpp
	g++ -c 6.11.cpp

6.12.o: 6.12.cpp
	g++ -c 6.12.cpp

6.17.o: 6.17.cpp
	g++ -c 6.17.cpp -std=c++11

6.21.o: 6.21.cpp
	g++ -c 6.21.cpp

6.22.o: 6.22.cpp
	g++ -c 6.22.cpp -std=c++11

6.23.o: 6.23.cpp
	g++ -c 6.23.cpp

6.25.o: 6.25.cpp
	g++ -c 6.25.cpp

6.26.o: 6.26.cpp
	g++ -c 6.26.cpp -std=c++11

6.27.o: 6.27.cpp
	g++ -c 6.27.cpp -std=c++11


6.33.o: 6.33.cpp
	g++ -c 6.33.cpp -std=c++11

6.51.o: 6.51.cpp
	g++ -c 6.51.cpp

6.55.o: 6.55.cpp
	g++ -c 6.55.cpp -std=c++11

6.56.o: 6.56.cpp
	g++ -c 6.56.cpp -std=c++11


.PHONY: clean
clean:
	rm 6.3 6.3.o \
	   6.4 6.4.o \
	   6.5 6.5.o \
	   6.6 6.6.o \
	   6.7 6.7.o \
	   fact.o \
	   factMain.o \
	   6.9 \
	   6.10 6.10.o \
	   6.11 6.11.o \
	   6.12 6.12.o \
	   6.17 6.17.o \
	   6.21 6.21.o \
	   6.22 6.22.o \
	   6.23 6.23.o \
	   6.25 6.25.o \
	   6.26 6.26.o \
	   6.27 6.27.o \
	   6.33 6.33.o \
	   6.51 6.51.o \
	   6.55 6.55.o \
	   6.56 6.56.o
