# Generated by Django 2.0.3 on 2018-04-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_myuser_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='user',
            new_name='myuser',
        ),
    ]
