######################################################################
# Automatically generated by qmake (3.0) Tue Mar 15 09:48:18 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = quit
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
