######################################################################
# Automatically generated by qmake (3.0) Tue Mar 15 11:24:28 2016
######################################################################

QT += widgets

TEMPLATE = app
TARGET = finddialog
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
